quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql


quarkus.oidc.application-type=web-app
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/
quarkus.oidc.logout.clear-site-data=cache,cookies

# Ne JAMAIS utiliser en production
# Les mots de passes doivent être forts, hachés et stockés de manière sécurisée
%dev.quarkus.keycloak.devservices.users.alice=alice
%dev.quarkus.keycloak.devservices.roles.alice=admin
%dev.quarkus.keycloak.devservices.users.bob=bob
%dev.quarkus.keycloak.devservices.roles.bob=user
%dev.quarkus.keycloak.devservices.users.eve=eve
%dev.quarkus.keycloak.devservices.roles.eve=user

quarkus.oidc.authentication.redirect-path=/
quarkus.http.auth.permission.authenticated.paths=/login,/logout,/eval/*,/messages/*,/profile/*,/admin/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.public.paths=/
quarkus.http.auth.permission.public.policy=permit
%noauth.quarkus.oidc.enabled=false
%noauth.quarkus.http.auth.permission.authenticated.policy=permit
%nginx.quarkus.http.proxy.proxy-address-forwarding=true
%nginx.quarkus.http.proxy.allow-x-forwarded=true
%nginx.quarkus.http.proxy.enable-forwarded-host=true
%nginx.quarkus.http.proxy.enable-forwarded-prefix=true
# decrypt token. Use only for demo.
%dev.quarkus.oidc.token-state-manager.encryption-required=false