quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.oidc.application-type=web-app

%dev.quarkus.keycloak.devservices.users.alice=alice
%dev.quarkus.keycloak.devservices.roles.alice=admin
%dev.quarkus.keycloak.devservices.users.bob=bob
%dev.quarkus.keycloak.devservices.roles.bob=user
%dev.quarkus.keycloak.devservices.users.eve=eve
%dev.quarkus.keycloak.devservices.roles.eve=user